version: '3.8'

services:
  voice-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
    restart: unless-stopped
